name: CIFAR
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - archspec=0.2.5=pyhd8ed1ab_0
  - aws-c-auth=0.8.1=h205f482_0
  - aws-c-cal=0.8.1=h1a47875_3
  - aws-c-common=0.10.6=hb9d3cd8_0
  - aws-c-compression=0.3.0=h4e1184b_5
  - aws-c-event-stream=0.5.0=h7959bf6_11
  - aws-c-http=0.9.2=hefd7a92_4
  - aws-c-io=0.15.3=h173a860_6
  - aws-c-mqtt=0.11.0=h11f4f37_12
  - aws-c-s3=0.7.9=he1b24dc_1
  - aws-c-sdkutils=0.2.2=h4e1184b_0
  - aws-checksums=0.2.2=h4e1184b_4
  - aws-crt-cpp=0.29.9=he0e7f3f_2
  - aws-sdk-cpp=1.11.489=h4d475cb_0
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - boltons=24.0.0=pyhd8ed1ab_1
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=24.11.3=py312h7900ff3_0
  - conda-libmamba-solver=24.9.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.11.0=pyhd8ed1ab_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - datasets=4.0.0=pyhcf101f3_0
  - dill=0.3.8=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - fmt=11.0.2=h434a139_0
  - frozendict=2.4.6=py312h66e93f0_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - h2=4.1.0=pyhd8ed1ab_1
  - hf-xet=1.2.0=py310hb823017_0
  - hpack=4.0.0=pyhd8ed1ab_1
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py312h7900ff3_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libarchive=3.7.7=h4585015_3
  - libarrow=19.0.1=hfa2a6e7_0_cpu
  - libarrow-acero=19.0.1=hcb10f89_0_cpu
  - libarrow-dataset=19.0.1=hcb10f89_0_cpu
  - libarrow-substrait=19.0.1=h08228c5_0_cpu
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=37_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.11.1=h332b0f4_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.35.0=h2b5623c_0
  - libgoogle-cloud-storage=2.35.0=h0121fbd_0
  - libgrpc=1.67.1=h25350d4_2
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=37_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmamba=1.5.12=h49b8a8d_0
  - libmambapy=1.5.12=py312hbaee817_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopentelemetry-cpp=1.18.0=hfcad708_1
  - libopentelemetry-cpp-headers=1.18.0=ha770c72_1
  - libparquet=19.0.1=h081d1f1_0_cpu
  - libprotobuf=5.28.3=h6128344_1
  - libre2-11=2024.07.02=hbbce691_2
  - libsolv=0.7.30=h3509ff9_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libthrift=0.21.0=h0e7cc3e_0
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=h0d44e9d_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - mamba=1.5.12=py312h9460a1c_0
  - menuinst=2.2.0=py312h7900ff3_0
  - multiprocess=0.70.16=py312h66e93f0_1
  - ncurses=6.5=h2d0b736_2
  - nlohmann_json=3.12.0=h54a6638_1
  - openssl=3.5.4=h26f9b46_0
  - orc=2.0.3=h12ee42a_2
  - pandas=2.3.3=py312hf79963d_1
  - pip=24.3.1=pyh8b19718_2
  - pluggy=1.5.0=pyhd8ed1ab_1
  - prometheus-cpp=1.3.0=ha5d0236_0
  - pyarrow-core=19.0.1=py312h01725c0_0_cpu
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py312h66e93f0_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.9=h9e4cc4f_1_cpython
  - python-gil=3.12.12=hd8ed1ab_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py312h0d868a3_0
  - python_abi=3.12=5_cp312
  - re2=2024.07.02=h9925aae_2
  - readline=8.2=h8228510_1
  - regex=2025.10.23=py312h4c3975b_0
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.3=pyhd8ed1ab_1
  - ruamel.yaml=0.18.10=py312h66e93f0_0
  - ruamel.yaml.clib=0.2.8=py312h66e93f0_1
  - s2n=1.5.11=h072c03f_0
  - safetensors=0.6.2=py312h0ccc70a_1
  - snappy=1.2.2=h03e3b7b_0
  - tk=8.6.13=noxft_h4845f30_101
  - tokenizers=0.22.1=py312h6be956c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.57.1=pyhd8ed1ab_0
  - truststore=0.10.0=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025a=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xxhash=0.8.3=hb47aa4a_0
  - yaml=0.2.5=h280c20c_3
  - yaml-cpp=0.8.0=h59595ed_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py312hef9b889_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - accelerate==1.11.0
      - adlfs==2023.8.0
      - aiohttp==3.11.16
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - alembic==1.17.0
      - amqp==5.3.1
      - annotated-types==0.6.0
      - anyio==3.7.1
      - attrs==25.1.0
      - azure-common==1.1.28
      - azure-core==1.29.5
      - azure-datalake-store==0.0.53
      - azure-identity==1.17.1
      - azure-storage-blob==12.22.0
      - billiard==4.2.1
      - blinker==1.9.0
      - boto3==1.29.7
      - botocore==1.32.7
      - cachetools==5.5.2
      - celery==5.5.3
      - certifi==2025.1.31
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1.2
      - click-repl==0.3.0
      - cloudpickle==3.1.1
      - colorful==0.5.5
      - contourpy==1.3.3
      - cryptography==44.0.3
      - cupy-cuda12x==13.1.0
      - cycler==0.12.1
      - cython==0.29.37
      - databricks-sdk==0.70.0
      - diffusers==0.35.2
      - distlib==0.3.7
      - dm-tree==0.1.8
      - docker==7.1.0
      - farama-notifications==0.0.4
      - fastapi==0.115.12
      - fastrlock==0.8.2
      - filelock==3.17.0
      - flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==23.5.26
      - fonttools==4.60.1
      - frozenlist==1.4.1
      - fsspec==2023.12.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.24.2
      - google-api-python-client==2.111.0
      - google-auth==2.23.4
      - google-auth-httplib2==0.1.1
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.14.0
      - google-crc32c==1.5.0
      - google-oauth==1.0.1
      - google-resumable-media==2.6.0
      - googleapis-common-protos==1.61.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - grpcio==1.74.0
      - gunicorn==23.0.0
      - gymnasium==1.1.1
      - h11==0.16.0
      - httplib2==0.20.4
      - httptools==0.7.1
      - idna==3.7
      - importlib-metadata==6.11.0
      - isodate==0.6.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.9
      - kombu==5.5.4
      - lz4==4.3.3
      - mako==1.3.10
      - markdown-it-py==2.2.0
      - markupsafe==2.1.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - memray==1.10.0
      - mlflow==3.5.1
      - mlflow-skinny==3.5.1
      - mlflow-tracing==3.5.1
      - mpmath==1.3.0
      - msal==1.28.1
      - msal-extensions==1.2.0b1
      - msgpack==1.0.7
      - multidict==6.0.5
      - networkx==3.5
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opentelemetry-api==1.34.1
      - opentelemetry-exporter-prometheus==0.55b1
      - opentelemetry-proto==1.27.0
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - ormsgpack==1.7.0
      - packaging==23.0
      - peft==0.17.1
      - pillow==12.0.0
      - platformdirs==3.11.0
      - portalocker==2.8.2
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.41
      - propcache==0.3.0
      - proto-plus==1.22.3
      - protobuf==4.25.8
      - psutil==5.9.6
      - py-spy==0.4.1
      - pyarrow==19.0.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.18.0
      - pyjwt==2.8.0
      - pyopenssl==25.0.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-dotenv==1.2.1
      - pytz==2022.7.1
      - pyyaml==6.0.1
      - ray==3.0.0.dev0
      - referencing==0.36.2
      - rich==13.3.2
      - rpds-py==0.22.3
      - rsa==4.7.2
      - s3transfer==0.8.0
      - scikit-learn==1.7.2
      - scipy==1.11.4
      - setuptools==80.9.0
      - six==1.16.0
      - smart-open==6.2.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - starlette==0.46.2
      - sympy==1.14.0
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.6.0
      - timm==1.0.21
      - torch==2.9.0
      - torchvision==0.24.0
      - triton==3.5.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - uritemplate==4.1.1
      - urllib3==1.26.19
      - uvicorn==0.22.0
      - uvloop==0.21.0
      - vine==5.1.0
      - virtualenv==20.29.1
      - watchfiles==0.19.0
      - wcwidth==0.2.13
      - websockets==11.0.3
      - werkzeug==3.1.3
      - yarl==1.18.3
      - zipp==3.19.2
