name: RESEARCH
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - archspec=0.2.5=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - bleach-with-css=6.2.0=h82add2a_4
  - boltons=24.0.0=pyhd8ed1ab_1
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=24.11.3=py312h7900ff3_0
  - conda-libmamba-solver=24.9.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.11.0=pyhd8ed1ab_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - fmt=11.0.2=h434a139_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - frozendict=2.4.6=py312h66e93f0_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_1
  - hpack=4.0.0=pyhd8ed1ab_1
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lark=1.3.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libarchive=3.7.7=h4585015_3
  - libcurl=8.11.1=h332b0f4_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=15.2.0=h767d61c_5
  - libgcc-ng=15.2.0=h69a702a_5
  - libgomp=15.2.0=h767d61c_5
  - libiconv=1.17=hd590300_2
  - liblzma=5.8.1=hb9d3cd8_2
  - libmamba=1.5.12=h49b8a8d_0
  - libmambapy=1.5.12=py312hbaee817_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsolv=0.7.30=h3509ff9_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=15.2.0=h8f9b012_5
  - libstdcxx-ng=15.2.0=h4852527_5
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=h0d44e9d_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - mamba=1.5.12=py312h9460a1c_0
  - menuinst=2.2.0=py312h7900ff3_0
  - ncurses=6.5=h2d0b736_2
  - openssl=3.5.4=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pip=24.3.1=pyh8b19718_2
  - pluggy=1.5.0=pyhd8ed1ab_1
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py312h66e93f0_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.9=h9e4cc4f_1_cpython
  - python-gil=3.12.12=hd8ed1ab_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - readline=8.2=h8228510_1
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - ruamel.yaml=0.18.10=py312h66e93f0_0
  - ruamel.yaml.clib=0.2.8=py312h66e93f0_1
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=pyhff2d567_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh0d859eb_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py312h4c3975b_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.0=pyhd8ed1ab_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h280c20c_3
  - yaml-cpp=0.8.0=h59595ed_0
  - zeromq=4.3.5=h387f397_9
  - zstandard=0.23.0=py312hef9b889_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - accelerate==1.11.0
      - adlfs==2023.8.0
      - aiofiles==22.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - aiosqlite==0.19.0
      - alembic==1.17.1
      - amqp==5.3.1
      - annotated-types==0.6.0
      - anyio==3.7.1
      - anyscale==0.26.63
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - attrs==25.1.0
      - azure-common==1.1.28
      - azure-core==1.29.5
      - azure-datalake-store==0.0.53
      - azure-identity==1.17.1
      - azure-storage-blob==12.22.0
      - babel==2.13.1
      - backcall==0.2.0
      - beautifulsoup4==4.11.1
      - billiard==4.2.1
      - bleach==6.1.0
      - blinker==1.9.0
      - boto3==1.29.7
      - botocore==1.32.7
      - cachetools==5.5.2
      - celery==5.5.3
      - certifi==2025.1.31
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1.2
      - click-repl==0.3.0
      - cloudpickle==3.1.1
      - colorful==0.5.5
      - comm==0.2.0
      - contourpy==1.3.3
      - cryptography==44.0.3
      - cupy-cuda12x==13.1.0
      - cycler==0.12.1
      - cython==0.29.37
      - databricks-sdk==0.73.0
      - debugpy==1.8.0
      - decorator==5.1.1
      - diffusers==0.35.2
      - distlib==0.3.7
      - dm-tree==0.1.8
      - docker==7.1.0
      - entrypoints==0.4
      - executing==2.0.1
      - farama-notifications==0.0.4
      - fastapi==0.115.12
      - fastjsonschema==2.19.0
      - fastrlock==0.8.2
      - filelock==3.17.0
      - flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==23.5.26
      - fonttools==4.60.1
      - frozenlist==1.4.1
      - fsspec==2023.12.1
      - gitdb==4.0.11
      - gitpython==3.1.44
      - google-api-core==2.24.2
      - google-api-python-client==2.111.0
      - google-auth==2.23.4
      - google-auth-httplib2==0.1.1
      - google-cloud-certificate-manager==1.10.2
      - google-cloud-common==1.5.2
      - google-cloud-compute==1.38.0
      - google-cloud-core==2.4.1
      - google-cloud-filestore==1.13.2
      - google-cloud-redis==2.18.1
      - google-cloud-resource-manager==1.14.2
      - google-cloud-secret-manager==2.24.0
      - google-cloud-storage==2.14.0
      - google-crc32c==1.5.0
      - google-oauth==1.0.1
      - google-resumable-media==2.6.0
      - googleapis-common-protos==1.61.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - grpc-google-iam-v1==0.14.2
      - grpcio==1.74.0
      - grpcio-status==1.62.3
      - grpcio-tools==1.62.3
      - gunicorn==23.0.0
      - gymnasium==1.1.1
      - hf-xet==1.2.0
      - httplib2==0.20.4
      - httptools==0.6.4
      - huey==2.5.4
      - huggingface-hub==0.36.0
      - humanize==4.12.1
      - idna==3.7
      - importlib-metadata==6.11.0
      - ipykernel==6.27.1
      - ipython==8.12.3
      - ipywidgets==8.1.3
      - isodate==0.6.1
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jmespath==1.0.1
      - joblib==1.5.2
      - json5==0.9.14
      - jsonpatch==1.32
      - jsonpointer==2.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==7.3.4
      - jupyter-core==5.5.0
      - jupyter-events==0.6.3
      - jupyter-server==1.24.0
      - jupyter-server-fileid==0.9.0
      - jupyter-server-terminals==0.4.4
      - jupyter-server-ydoc==0.6.1
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.1
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.9
      - kombu==5.5.4
      - log-symbols==0.0.14
      - lxml==4.9.4
      - lz4==4.3.3
      - mako==1.3.10
      - markdown-it-py==2.2.0
      - markupsafe==2.1.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - memray==1.10.0
      - mistune==0.8.4
      - mlflow==3.6.0
      - mlflow-skinny==3.6.0
      - mlflow-tracing==3.6.0
      - mpmath==1.3.0
      - msal==1.28.1
      - msal-extensions==1.2.0b1
      - msgpack==1.0.7
      - multidict==6.0.5
      - nbclassic==1.0.0
      - nbclient==0.5.13
      - nbconvert==6.5.4
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.5
      - notebook==6.5.7
      - notebook-shim==0.2.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - oauth2client==4.1.3
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opentelemetry-api==1.34.1
      - opentelemetry-exporter-prometheus==0.55b1
      - opentelemetry-proto==1.27.0
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - ormsgpack==1.7.0
      - packaging==23.0
      - pandas==2.3.3
      - parso==0.8.3
      - pathspec==0.11.2
      - peft==0.17.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==12.0.0
      - platformdirs==3.11.0
      - portalocker==2.8.2
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.41
      - propcache==0.3.0
      - proto-plus==1.22.3
      - protobuf==4.25.8
      - psutil==5.9.6
      - pure-eval==0.2.2
      - py-spy==0.4.1
      - pyarrow==19.0.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.18.0
      - pyjwt==2.8.0
      - pyopenssl==25.0.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-dotenv==1.1.1
      - pytz==2022.7.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - ray==2.50.0
      - referencing==0.36.2
      - regex==2025.11.3
      - rich==13.3.2
      - rpds-py==0.22.3
      - rsa==4.7.2
      - s3transfer==0.8.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.11.4
      - shellingham==1.5.4
      - six==1.16.0
      - smart-open==6.2.0
      - smmap==5.0.1
      - soupsieve==2.5
      - spinners==0.0.24
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - starlette==0.46.2
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - tinycss2==1.3.0
      - tokenizers==0.22.1
      - torch==2.9.0
      - torch-geometric==2.7.0
      - torchao==0.14.1
      - torchvision==0.24.0
      - transformers==4.57.1
      - triton==3.5.0
      - typer-slim==0.20.0
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzlocal==5.3
      - uritemplate==4.1.1
      - urllib3==1.26.19
      - uvicorn==0.22.0
      - uvloop==0.21.0
      - vine==5.1.0
      - virtualenv==20.29.1
      - watchfiles==0.19.0
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.11
      - wrapt==1.14.1
      - xxhash==3.6.0
      - y-py==0.6.2
      - yarl==1.18.3
      - ypy-websocket==0.8.4
      - zipp==3.19.2
